"use es6";

module.exports = {
  GET_START_LOCATION_AUTOCOMPLETE: "GET_START_LOCATION_AUTOCOMPLETE",
  GET_END_LOCATION_AUTOCOMPLETE: "GET_END_LOCATION_AUTOCOMPLETE",
  GET_START_COORDINATES: "GET_START_COORDINATES",
  GET_END_COORDINATES: "GET_END_COORDINATES"
};