"use es6";

module.exports = {
  GET_START_LOCATION_AUTOCOMPLETE: "GET_START_LOCATION_AUTOCOMPLETE",
  GET_END_LOCATION_AUTOCOMPLETE: "GET_END_LOCATION_AUTOCOMPLETE",
  GET_START_LOCATION_COORDINATES: "GET_START_LOCATION_COORDINATES",
  GET_END_LOCATION_COORDINATES: "GET_END_LOCATION_COORDINATES",
  GET_TIME_ESTIMATES: "GET_TIME_ESTIMATES",
  GET_COST_ESTIMATES: "GET_COST_ESTIMATES"
};